// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class GoogleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void google() {
    //Test name: google
    //Step # | name | target | value | comment
    //1 | open | / |  |
    driver.get("https://www.google.com/");
    // 2 | setWindowSize | 644x804 |  | 
    driver.manage().window().setSize(new Dimension(644, 804));
    // 3 | click | name=q |  | 
    driver.findElement(By.name("q")).click();
    // 4 | type | name=q | Selenium - Web Browser AutomaAion |
    driver.findElement(By.name("q")).sendKeys("Selenium - Web Browser AutomaATion");
    // 5 | sendKeys | name=q | ${KEY_ENTER} | 
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    // 6 | click | css=i |  | 
    driver.findElement(By.cssSelector("i")).click();
    // 7 | click | css=div:nth-child(2) > .rc .LC20lb |  | 
    driver.findElement(By.cssSelector("div:nth-child(2) > .rc .LC20lb")).click();
    // 8 | click | linkText=Download |  | 
    driver.findElement(By.linkText("Download")).click();
  }
  @Test
  public void google1() {
    //Test name: google
    //Step # | name | target | value | comment
    //1 | open | / |  |
    driver.get("https://www.google.com/");
    // 2 | setWindowSize | 644x804 |  |
    driver.manage().window().setSize(new Dimension(644, 804));
    // 3 | click | name=q |  |
    driver.findElement(By.name("q")).click();
    // 4 | type | name=q | Selenium - Web Browser AutomaAion |
    driver.findElement(By.name("q")).sendKeys("Selenium - Web Browser AutomaAion");
    // 5 | sendKeys | name=q | ${KEY_ENTER} |
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    // 6 | click | css=i |  |
    driver.findElement(By.cssSelector("i")).click();
    // 7 | click | css=div:nth-child(2) > .rc .LC20lb |  |
    driver.findElement(By.cssSelector("div:nth-child(2) > .rc .LC20lb")).click();
    // 8 | click | linkText=Download |  |
    driver.findElement(By.linkText("Download")).click();
  }
}

